*Vamos começar por funções básicas da Biblioteca:*

Primeiro vamos importar a Biblioteca

In [21]:
import numpy as np 
#importamos a biblioteca com o "apelido" np, assim qualquer chamada de método estático(função) será feita atravez desse apelido ao invés de escrever numpy

Primeiramente vamos criar nossos primeiros arrays(vetores) com Numpy

In [22]:
#Vale a pena lembrar que vetores possuem propriedades diferentes das listas do python

#primeira forma de estanciar um vetor com numpy
a = np.array([0, 2, 4, 6, 8, 10, 12, 14, 16, 18])

#segunda forma
b = np.arange(10)#essa função cria um vetor que parte do 0 e vai até o parametro -1

#criando uma matriz
x = ([(1, 2, 3), (4, 5, 6)])

#criando uma matriz de zeros
y = np.zeros((3,3))#os parametros definem as dimenções da matriz

print(f"a = {a} \n")
print(f"a = {b} \n")
print(f"a = {x} \n")
print(f"a = {y} \n")


a = [ 0  2  4  6  8 10 12 14 16 18] 

a = [0 1 2 3 4 5 6 7 8 9] 

a = [(1, 2, 3), (4, 5, 6)] 

a = [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 



Agora vamos fazer algumas operações básicas da biblioteca

In [23]:
c = a + b #Cria-se um novo Array com a soma dos elementos de mesmo indice dos vetores utilizados na conta
print(c)

[ 0  3  6  9 12 15 18 21 24 27]


In [24]:
d = a + b #Cria-se um novo Array com a subtração dos elementos de mesmo indice dos vetores utilizados na conta
print(d)

[ 0  3  6  9 12 15 18 21 24 27]


In [25]:
e = a + b #Cria-se um novo Array com a multiplicação dos elementos de mesmo indice dos vetores utilizados na conta
print(e)

[ 0  3  6  9 12 15 18 21 24 27]


In [37]:
f = a // b #Cria-se um novo Array com a divisão inteira entre elementos de mesmo indice dos vetores utilizados na conta
print(f)

[0 2 1 1 1 1 1 1 1 1]


C:\Users\Caio\AppData\Local\Temp\ipykernel_21984\1867375452.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  f = a // b #Cria-se um novo Array com a divisão entre elementos de mesmo indice dos vetores utilizados na conta


In [27]:
g = a ** b #Cria-se um novo Array com a exponenciação dos elementos de mesmo indice dos vetores utilizados na conta
print(g)

[        1         2        16       216      4096    100000   2985984
 105413504         0 790794752]


In [28]:
h = a > 5 #Cria-se um novo Array com o valor booleano correspondente a operação lógica de comparação relativo a cada elemento do array
print(h)

[False False False  True  True  True  True  True  True  True]


Métodos auxiliares

In [36]:
print(f"Soma = {a.sum()}")#soma de todos os elementos do array
print(f"Média = {a.mean()}")#Valor medio dos elementos do array

print(f"Maior elemento = {a.max()}")#retorna o maior número do array
print(f"Menor elemento = {a.min()}")#retorna o menor número do array

Soma = 55
Média = 5.5
Maior elemento = 10
Menor elemento = 1


Siling(selecionar os dados do array)

In [30]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])#sobrescrevendo o array anterior para facilitar o entendimento

In [31]:
a[2]#selecionando o elemento do indice escrito

3

In [32]:
a[-1]#selecionando o último elemento do array

10

In [33]:
a[2:5]#seleciona os elementos de índice 2 ao 5

array([3, 4, 5])

In [34]:
a[6:]#seleciona os elementos do índice 6 ao fim o vetor

array([ 7,  8,  9, 10])

In [35]:
a[:6]#seleciona os elementos desde o inicio ao de índice 6

array([1, 2, 3, 4, 5, 6])